# SPDX-FileCopyrightText: 2026 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD
[test_config]
locked = true
offline = true
engine = "Llvm"
test-timeout = "1m"
target-dir = ".tarpaulin"
packages = ["ial-core", "ial-ast", "ial"]
exclude-files = ["target/*"]
out = [ "Html" ]
skip-clean = true
